services:
    nginx:
        build:
            context: ./
            dockerfile: docker/nginx.docker
        volumes:
            - ./:/var/www
            - ./docker/nginx/ssl:/etc/nginx/ssl
            - ./logs/nginx:/var/log/nginx
        ports:
            - "8080:80"
        depends_on:
            - php-fpm
    php-fpm:
        build:
            context: ./
            dockerfile: docker/php-fpm.docker
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
            - redis
            - elasticsearch
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
            - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
    php-cli:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
            - redis
            - elasticsearch
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
            - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
        tty: true
    horizon:
        build:
            context: ./
            dockerfile: docker/php-cli.docker
        volumes:
            - ./:/var/www
        depends_on:
            - mysql
            - redis
            - elasticsearch
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=mysql"
            - "REDIS_PORT=6379"
            - "REDIS_HOST=redis"
            - "ELASTICSEARCH_HOSTS=elasticsearch:9200"
        command: php artisan horizon
        restart: unless-stopped
    mysql:
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./storage/docker/mysql:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=app"
        ports:
            - "33061:3306"
    redis:
        image: redis:7-alpine
        ports:
            - "63791:6379"
    node:
        image: node:20-alpine
        volumes:
            - ./:/var/www
        working_dir: /var/www
        tty: true
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        environment:
            - discovery.type=single-node
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        volumes:
            - ./storage/docker/elasticsearch:/usr/share/elasticsearch/data
        ports:
            - "9201:9200"